# Generated by Django 5.2.17 on 2026-08-14 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('skills_required', models.CharField(blank=True, max_length=400)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(blank=True, max_length=80)),
                ('education_required', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(db_index=True, max_length=160)),
                ('work_mode', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='NPR', max_length=8)),
                ('number_of_openings', models.PositiveIntegerField(default=1)),
                ('application_deadline', models.DateField(db_index=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='draft', max_length=12)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'application_deadline'], name='jobs_job_status_e53abc_idx')],
            },
        ),
    ]
